### ISSUE TITLE
Which build should I download?

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/FFmpeg-Builds#10]
Which build should I use? I use 64-bit windows, so that narrows me down to 8, and apparently the GPL builds have more features, and I don't mind a stricter license, so that narrows me down to 4, but what is the difference between these 4?

win64-gpl-4.4
win64-gpl-shared-4.4
win64-gpl-shared
win64-gpl

**Comment by pukkandan** [comment]
`shared` means it's dynamically linked and you need to keep the dll files
`5` is the latest release version, `4.4` is the 4.4 release version and the other is master branch
For most people, just go with GPL ~~master~~ release (not shared)

The recommended downloads are in the readme: https://github.com/yt-dlp/FFmpeg-Builds#downloads

**Comment by gamer191** [comment]
thanks :)

**Comment by ImArghya7** [comment]
@pukkandan 
What is the difference between these two:
ffmpeg-master-latest-win64-gpl.zip
ffmpeg-n5.1-latest-win64-gpl-5.1.zip

**Comment by Lesmiscore** [comment]
master is development and n5.1 is release

**Comment by ImArghya7** [comment]
So, which one should one download?

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/187938919-f8de8cf2-0fe0-4a57-8c14-fcfb735b4383.png)

**Comment by ImArghya7** [comment]
![2022-09-01_21-07](https://user-images.githubusercontent.com/22514844/187955295-f8401db3-e26e-4743-81e2-3d1cb707c1d1.png)

When I clicked on the "Windows x64" option "ffmpeg-master-latest-win64-gpl.zip" started downloading.

But then as per @Lesmiscore 

> master is development and n5.1 is release

So I'm assuming "ffmpeg-master-latest-win64-gpl.zip" = Beta & "ffmpeg-n5.1-latest-win64-gpl-5.1.zip" = Stable

Correct me if I'm wrong.

**Comment by Korb** [comment]
In conclusion, it can be said that for most users it is enough to download and unpack the archive `ffmpeg-n7.0-latest-win64-gpl-7.0.zip`. However, I doubt that this alone will solve the error

> WARNING: ffmpeg not found. The downloaded format may not be the best available. **Installing** ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

The word `install` does not appear in README.md.

**Comment by nihil-admirari** [comment]
After unpacking, the path to FFmpeg must be either added to `$PATH` or supplied as `--ffmpeg-location`.
