### ISSUE TITLE
How to use?..

### ISSUE THREAD

**Issue by jcn50** [yt-dlp/FFmpeg-Builds#12]
I am on Linux: how to use and what to run when you have ffmpeg installed from the repo?..

**Comment by jcn50** [comment]
OK you can close, I finally found it:

`apt remove -y ffmpeg && ./makeimage.sh linux64 gpl && /build.sh linux64 gpl`

**Comment by jcn50** [comment]
That shit does not work, it's having a hard time pulling the repos over a simple HTTPS call:
```
 => [layer-45-x11  3/18] RUN --mount=src=scripts.d/45-x11/10-xtrans.sh,dst=/stage.sh run_stage /stage.sh                                                          78.8s
 => => # hint: 'development'. The just-created branch can be renamed via this command:
 => => # hint:
 => => # hint: git branch -m <name>
 => => # Initialized empty Git repository in /stage/libxtrans/.git/
 => => # + git -C libxtrans remote add origin https://gitlab.freedesktop.org/xorg/lib/libxtrans.git
 => => # + git -C libxtrans fetch --depth=1 origin 3b5df889f58a99980a35a7b4a18eb4e7d2abeac4

```

Intead of wasting everybody's CPU why not just compile static executable of ffmpeg once and share that? Docker buildx is crap and a flawed idea.

Happy New Year 2022 to idiots like me!

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/FFmpeg-Builds/wiki/Latest

**Comment by jcn50** [comment]
> https://github.com/yt-dlp/FFmpeg-Builds/wiki/Latest

**CHEERS!!**
