### ISSUE TITLE
Which build should I download for yt-dlp?

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/FFmpeg-Builds#14]
![image](https://user-images.githubusercontent.com/36833664/150672716-eab49461-0c88-44c8-a040-f3af939b23f3.png)
![image](https://user-images.githubusercontent.com/36833664/150672763-98480795-805c-4967-96d5-87e25f9a340a.png)
![image](https://user-images.githubusercontent.com/36833664/150672853-dc86c610-218b-43b9-b8b5-ccba7d3eec64.png)

**Comment by pukkandan** [comment]
Pinned issue!
