### ISSUE TITLE
No support for ARM (raspberry pi 4)

### ISSUE THREAD

**Issue by aidenator** [yt-dlp/FFmpeg-Builds#15]
It would be nice to provide these custom ffmpeg builds for ARM. I'm using a raspberry pi 4 on Ubuntu Server and have to use the builds that Ubuntu (apt install) provides. They work about 90% of the time, but occasionally I'll get these errors:
`ERROR: Postprocessing: Conversion failed!`

Attached is the full verbose output, curious that python threw an exception too.
[ytdlp_ffmpeg_error.txt](https://github.com/yt-dlp/FFmpeg-Builds/files/8004968/ytdlp_ffmpeg_error.txt)

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/FFmpeg-Builds#1-macosarm-builds
