### ISSUE TITLE
how to install on ubuntu 

### ISSUE THREAD

**Issue by jayvgithub** [yt-dlp/FFmpeg-Builds#19]
how to install on ubuntu

**Comment by gamer191** [comment]
Are you using this with yt-dlp?
If yes, which method did you use to install yt-dlp?

**Comment by nihil-admirari** [comment]
Just unpack the archive:

```sh
tar xf ffmpeg-master-latest-linux64-gpl.tar.xz -C /opt
```

Then either add `/opt/ffmpeg-master-latest-linux64-gpl/bin` to `PATH`, or use `--ffmpeg-location` command line argument.

P.S. Strictly specking, you no longer need this build on Linux. Patches here only enable long path support on Windows. Everything else was already merged into FFmpeg `master`.

**Comment by Goldmaster** [comment]
> P.S. Strictly specking, you no longer need this build on Linux. Patches here only enable long path support on Windows. Everything else was already merged into FFmpeg `master`.

So are you saying just install normal ffmpeg with sudo apt install ffmpeg?

**Comment by gamer191** [comment]
@Goldmaster that comment is outdated. These builds now fix https://github.com/yt-dlp/yt-dlp/issues/4127, which does affect Linux. Also, `sudo apt install ffmpeg` won't install FFmpeg master, it will install FFmpeg's latest* stable release, which doesn't yet fix https://github.com/yt-dlp/yt-dlp/issues/871. So you should use these builds if you care about either of those issues. But otherwise, `sudo apt install ffmpeg` is probably fine

*actually, it will probably be a few versions behind, depending on your Linux distro

**Comment by Goldmaster** [comment]
Ah ok, im on debian. So I guess it wait a bit till it worked it's way into the main release?

**Comment by Winston6079** [comment]
@nihil-admirari  Sorry if im making a basic question, but how do you add /opt/ffmpeg-master-latest-linux64-gpl/bin to PATH

**Comment by nihil-admirari** [comment]
Depends on your shell, see e.g.: https://unix.stackexchange.com/a/26059.

With Bash, adding to `~/.bash_profile` and doing a re-login should work:
```bash
export PATH="/opt/ffmpeg-master-latest-linux64-gpl/bin:$PATH"
```

**Comment by sebma** [comment]
@nihil-admirari 
> Then either add `/opt/ffmpeg-master-latest-linux64-gpl/bin` to `PATH`, or use `--ffmpeg-location` command line argument.

Just to be a little more explicit, did you mean ? : `yt-dlp --ffmpeg-location PATH`

**Comment by nihil-admirari** [comment]
```sh
yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin
```

**Comment by Ray7788** [comment]
> ```shell
> yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin
> ```
Hi there,
Unfortunately I tried but failed. I checked the latest README and it says "Now this command is no longer documented."

**Comment by nihil-admirari** [comment]
`--ffmpeg-location` is still documented in https://github.com/yt-dlp/yt-dlp. Have you typed

```sh
yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin OTHER_OPTIONS_SUCH_AS_VIDEO_ID
```

or just literally

```sh
yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin
```

**Comment by Ray7788** [comment]
> `--ffmpeg-location` is still documented in https://github.com/yt-dlp/yt-dlp. Have you typed
> 
> ```shell
> yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin OTHER_OPTIONS_SUCH_AS_VIDEO_ID
> ```
> 
> or just literally
> 
> ```shell
> yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin
> ```

Thank you for your reply! I tried the second one and it failed, now it works(but I didn't try the 1st one, that's weird), anyway thank you for your help!

**Comment by ufkhf** [comment]
> `--ffmpeg-location` is still documented in https://github.com/yt-dlp/yt-dlp. Have you typed
> 
> ```shell
> yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin OTHER_OPTIONS_SUCH_AS_VIDEO_ID
> ```
> 
> or just literally
> 
> ```shell
> yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin
> ```

Hi, when i tried the 2 commands, it didnt work. I uploaded a screenshot of the terminal.

**Comment by ufkhf** [comment]
![Uploading Screenshot from 2024-09-07 21-17-49.png…]()

**Comment by ufkhf** [comment]
![Terminal](https://github.com/user-attachments/assets/48c7246c-e3b7-4f7e-8803-7ad61537e66b)

**Comment by seproDev** [comment]
@ufkhf 
You don't literally need to write `OTHER_OPTIONS_SUCH_AS_VIDEO_ID`, but need to provide a video URL you want to download or some other command line options. So for example:
```
yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin "https://www.youtube.com/watch?v=2yJgwwDcgV8"
```

Also don't use sudo.

**Comment by ufkhf** [comment]
Is it possible to install it, so i dont have to do each time: yt-dlp --ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin.

**Comment by seproDev** [comment]
Either add ffmpeg to your path, or add `--ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin` to your yt-dlp config file.
Though generally, unless you are on a really ancient OS, I would recommend just installing FFmpeg from your distro instead.

**Comment by Lohita9** [comment]
> Either add ffmpeg to your path, or add `--ffmpeg-location /opt/ffmpeg-master-latest-linux64-gpl/bin` to your yt-dlp config file. Though generally, unless you are on a really ancient OS, I would recommend just installing FFmpeg from your distro instead.

@seproDev how to install this package using GitHub action?

I used this, but it’s not working for me.
```yml
wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
tar xf ffmpeg-master-latest-linux64-gpl.tar.xz -C /opt
echo "/opt/ffmpeg-master-latest-linux64-gpl/bin" >> $GITHUB_PATH
```
