### ISSUE TITLE
How to enable hardware acceleration?

### ISSUE THREAD

**Issue by Xan-Kun** [yt-dlp/FFmpeg-Builds#20]
First of all: Thanks for the fork!
This isn't really an issue and more of a question.
I try to enable **d3d11va** hardware acceleration using the command
```
--postprocessor-args='-hwaccel d3d11va'
```
in the last line of the config-file.
But I only get an error
```
### ERROR: Postprocessing: Error opening output files: Invalid argument
```

I am aware this might not be the right place to ask and I would love to ask again or repost this in a better place if anyone knows the answer.

**Comment by nihil-admirari** [comment]
From the [docs](https://github.com/yt-dlp/yt-dlp):
```
--postprocessor-args NAME:ARGS        ... Specify the postprocessor/executable name
                                      and the arguments separated by a colon ":" ...
```
I don't see the `NAME` in your `--postprocessor-args`, only `ARGS`.

If it still doesn't work after specifying the `NAME`, please provide verbose logs (`-v` argument), so that we can see how FFmpeg is actually invoked.

**Comment by pukkandan** [comment]
Is hwacel meant to be an input arg, or an output arg? If input, you'll have to do `--ppa "ffmpeg_i:-hwaxel ..."`

**Comment by Xan-Kun** [comment]
> Is hwacel meant to be an input arg, or an output arg? If input, you'll have to do `--ppa "ffmpeg_i:-hwaxel ..."`

Holemoley & OMG! It worked at first try and mergin of 30min video is down from ~2Minutes to like a few seconds.

Thank you so much! Really appreciate the time you took to anwer. Please have a wonderful day.

Edit: Sorry, from all the excitement I forgot to paste the actual working line.

In yt-dlp.config file (but should also work from command line)
`--ppa "ffmpeg_i:-hwaccel auto"`
btw, depending on system is the same as
`--ppa "ffmpeg_i:-hwaccel d3d11va"`
