### ISSUE TITLE
Build fails - patch doesnt apply

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/FFmpeg-Builds#21]
https://github.com/yt-dlp/FFmpeg-Builds/commit/8d832302b30e223d8fde0ed3dd0938d097811e39 no longer applies. @nihil-admirari could you please take a look?

**Comment by gamer191** [comment]
I'm not sure how helpful this is, but I deleted FFmpeg patch 0004 and attempted to build it, and it still failed (see https://github.com/gamer191/FFmpeg-Builds/actions/runs/2047923988). It's possible though that patch 0005 relies on patch 0004.

I'm now trying it with both patch 0004 and 0005 deleted (see here, but it's no where near finished yet https://github.com/gamer191/FFmpeg-Builds/actions/runs/2050710264)

**Comment by gamer191** [comment]
Building with both patch 0004 and 0005 deleted failed (see https://github.com/gamer191/FFmpeg-Builds/actions/runs/2050710264). Lets try now with 0004, 0005 and 0006 all deleted: https://github.com/gamer191/FFmpeg-Builds/actions/runs/2050742188 (EDIT: it succeeded)

**Comment by nihil-admirari** [comment]
Fixed: https://github.com/yt-dlp/FFmpeg-Builds/actions/runs/2054925305.

[FFmpeg patches](https://github.com/yt-dlp/FFmpeg-Builds/tree/master/patches/ffmpeg) are now grouped by branch name. Even if some patches can be applied to different branches, they have to be duplicated.

**Comment by pukkandan** [comment]
thanks
