### ISSUE TITLE
How do I build this from source?

### ISSUE THREAD

**Issue by menkaur** [yt-dlp/FFmpeg-Builds#22]
When I run build.sh, it fails saying that I'm not providing enough arguments.
Could you explain how to build this from source?

**Comment by nihil-admirari** [comment]
Please take a look at [`build.yml`](https://github.com/yt-dlp/FFmpeg-Builds/blob/master/.github/workflows/build.yml).

You need to build three Docker images, and only after that `./build.sh ${{ matrix.target }} ${{ matrix.variant }}`. Full list of targets and variants is in [upstream's readme](https://github.com/BtbN/FFmpeg-Builds#targets-variants-and-addins).

If you don't want to build Docker images, you can fetch them from GitHub: https://github.com/orgs/yt-dlp/packages.

**Comment by pukkandan** [comment]
These type of questions should ideally go to the upstream project https://github.com/BtbN/FFmpeg-Builds. The only change we have made is to add the patches. Everything else is same
