### ISSUE TITLE
Windows master builds failing

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/FFmpeg-Builds#24]
The Windows builds of the master branch are [failing](https://github.com/yt-dlp/FFmpeg-Builds/actions/workflows/build.yml)

I'm going to try to run tests to see which patch is causing the error (but I can't help much beyond that)

[Test 1](https://github.com/gamer191/FFmpeg-Builds/actions/runs/2408376242): does ffmpeg build successfully if the last 3 patches are [deleted](https://github.com/gamer191/FFmpeg-Builds/commit/e5294f55e9649190f7b81c5304583a4f97ceaaf8)?
Result: no (potentially caused by interference from the [scheduled build](https://github.com/gamer191/FFmpeg-Builds/actions/runs/2408989612), but I highly doubt it, based on the log)

[Test 2](https://github.com/gamer191/FFmpeg-Builds/actions/runs/2409514857): Does it build if we [delete patches 2-6](https://github.com/gamer191/FFmpeg-Builds/commit/61e27427d8f1b63630eab0d0b92e2bc896bc9e80) (so only patch 1 applies)?
Result: workflow failed, due to permissions error, but the part that was failing succeeded, so I'm calling it a success

[Test 3](https://github.com/gamer191/FFmpeg-Builds/actions/runs/2409778203): Does it build with patches 3-6 [deleted](https://github.com/gamer191/FFmpeg-Builds/commit/5d3edaf2e636e3131d235bdb5add2189fa7a8221)?
Result: workflow failed, due to error pruning old releases, but the part that was failing succeeded, so I'm calling it a success

As such, patch 3 is the problematic patch

CC @nihil-admirari

**Comment by gamer191** [comment]
I'm testing [here](https://github.com/gamer191/FFmpeg-Builds/actions/runs/2406495674) to see whether one of the last 3 patches is responsible for the error

**Comment by nihil-admirari** [comment]
```
In file included from libavcodec/mfenc.c:32:
./compat/w32dlfcn.h: In function 'win32_dlopen':
./compat/w32dlfcn.h:62:9: error: implicit declaration of function 'utf8towchar' [-Werror=implicit-function-declaration]
   62 |     if (utf8towchar(name, &name_w))
      |         ^~~~~~~~~~~
```

Made `wchar_filename.h` include unconditional:
```c
-#if (_WIN32_WINNT < 0x0602) || HAVE_WINRT
 #include "libavutil/wchar_filename.h"
-#endif
```

**Comment by gamer191** [comment]
Thanks
