### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/FFmpeg-Builds#27]
Patch one is not applying on the master builds

EDIT: Actually, it appears that patch one was applied to master in https://github.com/FFmpeg/FFmpeg/commit/cc5844da988fb7ca1051775a3dac43de77bf3881, so it can probably just be deleted

EDIT 2: Actually, it appears (I didn't look super closely) that all 5 patches were merged into master:
Patch 1-https://github.com/FFmpeg/FFmpeg/commit/cc5844da988fb7ca1051775a3dac43de77bf3881
Patch 2-https://github.com/FFmpeg/FFmpeg/commit/dfa062ed3cae1d7ae3fdc52c7adda09cfc2e29b9
Patch 3-https://github.com/FFmpeg/FFmpeg/commit/13350e81fd43cbd1aa3bbb7ed567e7dc7dd2b7f5
Patch 4-https://github.com/FFmpeg/FFmpeg/commit/c381f5412fe810bd8118123aed9bd4f76b75b59d
Patch 5-https://github.com/FFmpeg/FFmpeg/commit/69364a06c65d3437e8158cdffd98c2f6d1b84dd2
In my opinion this repo should stay up though, so that ~~all~~ most yt-dlp users use the same builds, with the same codecs compiled, and we won't encounter any issues of people using ffmpeg lite etc. Also, this repo should stay up for when https://github.com/yt-dlp/FFmpeg-Builds/pull/26 gets merged

**Comment by gamer191** [comment]
Actually, it appears that patch one was applied to master in https://github.com/FFmpeg/FFmpeg/commit/cc5844da988fb7ca1051775a3dac43de77bf3881, so it can probably just be deleted

**Comment by gamer191** [comment]
Actually, it appears (I didn't look super closely) that all 5 patches were merged into master:
Patch 1-https://github.com/FFmpeg/FFmpeg/commit/cc5844da988fb7ca1051775a3dac43de77bf3881
Patch 2-https://github.com/FFmpeg/FFmpeg/commit/dfa062ed3cae1d7ae3fdc52c7adda09cfc2e29b9
Patch 3-https://github.com/FFmpeg/FFmpeg/commit/13350e81fd43cbd1aa3bbb7ed567e7dc7dd2b7f5
Patch 4-https://github.com/FFmpeg/FFmpeg/commit/c381f5412fe810bd8118123aed9bd4f76b75b59d
Patch 5-https://github.com/FFmpeg/FFmpeg/commit/69364a06c65d3437e8158cdffd98c2f6d1b84dd2

In my opinion this repo should stay up, so that ~~all~~ most yt-dlp users use the same builds, with the same codecs compiled, and we won't encounter any issues of people using ffmpeg lite etc. Also, this repo should stay up to host https://github.com/yt-dlp/FFmpeg-Builds/pull/26

**Comment by nihil-admirari** [comment]
> all 5 patches were merged into master

True.

> Also, this repo should stay up for when #26 gets merged

Merged.

**Comment by pukkandan** [comment]
Keeping this pinned so that a new issue doesn't need to be opened every time a rebase fails

**Comment by gamer191** [comment]
The rebase is failing again, because of a merge conflict in the .gitignore file

**Comment by pukkandan** [comment]
fixed

**Comment by gamer191** [comment]
The builds are failing again :(

**Comment by nihil-admirari** [comment]
Upstream problem: https://github.com/BtbN/FFmpeg-Builds/issues/182.

**Comment by gamer191** [comment]
Thanks @nihil-admirari 
On a side note, it's been fixed upstream, https://github.com/BtbN/FFmpeg-Builds/commit/512e0fe9b4851983ceaffb588960cea715e9cad8, so now I guess it's just a matter of waiting for the next `Rebase on Upstream` (in approximately 9 hours)

**Comment by gamer191** [comment]
~~`Rebase on Upstream` is failing again, due to a conflict with https://github.com/BtbN/FFmpeg-Builds/commit/d4de0513b5b937644c9938e517798d04bcd9b8e7~~
That said, there's no urgency to fix it, because Pukkandan manually ran `Rebase on Upstream` earlier, so https://github.com/yt-dlp/FFmpeg-Builds/commit/512e0fe9b4851983ceaffb588960cea715e9cad8 has already made it's way onto this repo (`Build FFmpeg` is running right now, fingers crossed it succeeds)

EDIT: it's working again :)

**Comment by gamer191** [comment]
The builds are failing again

**Comment by nihil-admirari** [comment]
Must be fixed upstream: https://github.com/BtbN/FFmpeg-Builds/commit/915d6e0afa023bafe32a334febfbd8bc6d76ff52#commitcomment-115905755.

**Comment by gamer191** [comment]
The builds are failing again, although the error message makes it sound like it's an issue on Github's end

**Comment by gamer191** [comment]
The builds are failing every few days with `connection reset by peer`. I'm not sure if I should report that here or open a new issue?

**Comment by gamer191** [comment]
The builds are failing again. I'll look into this tomorrow if I have time

**Comment by gamer191** [comment]
Rebase on Upstream is failing again
