### ISSUE TITLE
Plans to upstream patches? Or provide a debian/ubuntu PPA?

### ISSUE THREAD

**Issue by turian** [yt-dlp/FFmpeg-Builds#30]
Are there any plans to upstream these patches? Or at least provide a PPA for simple installation (and making sure that this ffmpeg is used and not the standard debian/ubuntu one)?

**Comment by shirt-dev** [comment]
Many of these patches have already been merged into FFmpeg, and the FFmpeg team is free to use these patches (the one patch currently in use has already been submitted to their mailing list).

There are no plans to submit these builds to package managers.

**Comment by pukkandan** [comment]
> Many of these patches have already been merged into FFmpeg, and the FFmpeg team is free to use these patches (the one patch currently in use has already been submitted to their mailing list).

To expand on this, we only accept patches that have already been submitted to the upstream team. These builds exist to just make unmerged patches available, and does not intend to be a real fork of ffmpeg
