### ISSUE TITLE
Windows ARM/MacOS builds

### ISSUE THREAD

**Issue by sirzooro** [yt-dlp/FFmpeg-Builds#34]
Hi,
I just want to let you know that BOINC project has workflows for Windows ARM and MacOS. You can check how they do this and modify your ones: https://github.com/BOINC/boinc

**Comment by pukkandan** [comment]
That project seems to have nothing to do with ffmpeg?

**Comment by sirzooro** [comment]
Yes, it is completely different project - it is platform for distributed scientific calculations. I though that you could check it for general steps how to create workflows for additional platforms.

**Comment by pukkandan** [comment]
The issue is not with running on MacOS, it's porting this workflow into that platform
