### ISSUE TITLE
Creating security context failed (0x80090300)

### ISSUE THREAD

**Issue by TehLandstander** [yt-dlp/FFmpeg-Builds#35]
Streams fail to download with the above error.

This is an issue carried over from BtbN's build.  According to user smitelli, it is because it is compiled without TLS v1.2 support.

**Comment by pukkandan** [comment]
Unless you are able to make a PR fixing it, pls report it to upstream instead. We only take upstream code and add existing patches

**Comment by nihil-admirari** [comment]
1. What are you trying to do exactly?
2. Are you on Windows? If so, can you please retest on Linux? (mbedtls apparently [is not even enabled](https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-librist/40-mbedtls.sh#L26) on Windows.)
3.  > According to user smitelli, it is because it is compiled without TLS v1.2 support.

    Please give his full response.

**Comment by TehLandstander** [comment]
I'm using Windows, and admittedly I recently reconfigured my network with a multiwan setup.  I could be the second ISP.  It could be the source links are coming from one ISP and then ffmpeg is being routed to another.
Still, I had to change my ffmpeg as a result and it now works fine.
Searching for the solution I found back in 2020 YouTube-dl users were apparently using BtbN versions: https://github.com/ytdl-org/youtube-dl/issues/9392#issuecomment-740259976
And, no, I would have no idea how to test on Linux.

**Comment by nihil-admirari** [comment]
> Still, I had to change my ffmpeg as a result and it now works fine.

Have you updated your FFmpeg to a newer release and now everything's fine? Or have you switched to a completely different distribution, e.g. `gyan.dev`'s one?

> And, no, I would have no idea how to test on Linux.

Well, you basically execute the same command you've executed on Windows, but on a Linux machine with Linux builds of FFmpeg. Virtual machine/WSL should be fine too. At the very least: provide the command that gave you 0x80090300.

Also 0x800... looks surprisingly like a Windows error, not an FFmpeg one. @smitelli's 0x80090304 may indeed be [related to TLS version mismatch](https://stackoverflow.com/questions/37925505/a-call-to-sspi-failed-see-inner-exception-the-local-security-authority-cannot):
```cmd
> certutil.exe -error 0x80090304
0x80090304 (-2146893052 SEC_E_INTERNAL_ERROR) -- 2148074244 (-2146893052)
Error message text: The Local Security Authority cannot be contacted
```

0x80090300, however, is entirely different:
```cmd
> certutil.exe -error 0x80090300
0x80090300 (-2146893056 SEC_E_INSUFFICIENT_MEMORY) -- 2148074240 (-2146893056)
Error message text: Not enough memory is available to complete this request
```

**Comment by TehLandstander** [comment]
I don't know about those errors.  The thread I linked, and the error I got is the title of this thread: 
`[tls @ 000000000054c880] Creating security context failed (0x80090326)`

And, yeah, gyan.dev's release fixed it.

**Comment by nihil-admirari** [comment]
That's a third error in a row:
```cmd
> certutil.exe -error 0x80090326
0x80090326 (-2146893018 SEC_E_ILLEGAL_MESSAGE) -- 2148074278 (-2146893018)
Error message text: The message received was unexpected or badly formatted.
```
It's different from the previous two.

Still, how you're invoking `ffmpeg` exactly?
```cmd
ffmpeg.exe ...
```
What is there instead of three dots? If you're using `yt-dlp`, `yt-dlp --verbose` will show invocation in logs.

**Comment by TehLandstander** [comment]
> That's a third error in a row:
> 
> ```batchfile
> > certutil.exe -error 0x80090326
> 0x80090326 (-2146893018 SEC_E_ILLEGAL_MESSAGE) -- 2148074278 (-2146893018)
> Error message text: The message received was unexpected or badly formatted.
> ```
> 
> It's different from the previous two.
> 
> Still, how you're invoking `ffmpeg` exactly?
> 
> ```batchfile
> ffmpeg.exe ...
> ```
> 
> What is there instead of three dots? If you're using `yt-dlp`, `yt-dlp --verbose` will show invocation in logs.

Is your question even about this thread?  I have no idea what you're talking about, or even quoting.

**Comment by nihil-admirari** [comment]
> Is your question even about this thread? I have no idea what you're talking about, or even quoting.

Of course it is. Unless you specify how you've called `ffmpeg.exe` exactly, I won't be able to even reproduce an issue.

I repeat my question: in command line, you've typed `ffmpeg.exe ...` and it gave you 0x80090300. How `ffmpeg.exe ...` looks like exactly?

If you use yt-dlp, then please go with the steps from [yt-dlp issue template](https://github.com/yt-dlp/yt-dlp/blob/master/.github/ISSUE_TEMPLATE/4_bug_report.yml):

> Provide verbose output that clearly demonstrates the problem:
> - Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>) *
> - If using API, add 'verbose': True to YoutubeDL params instead
> - Copy the WHOLE output (starting with [debug] Command-line config) and insert it below *

**Comment by TehLandstander** [comment]
Okay.  Those errors you posted weren't anything I had seen.
Now, like I said, I am load balancing two ISPs, so that may be the issue.  I can try bypassing that and testing each ISP individually later.

As far as how I was testing ffmpeg, it's about the same as I have for the past 5 years.
`ffmpeg.exe -i "%stream%"  -c copy -bsf:a aac_adtstoasc "output.mp4"`

I get: `[tls @ 00000000004cc740] Creating security context failed (0x80090326)
https://(link): Unknown error occurred`

Testing with yt-dlp actually does work, but that could be getting routed to a different ISP.
`yt-dlp .exe --downloader ffmpeg.exe https://(link) -o "output.mp4"`

**Comment by nihil-admirari** [comment]
>  Those errors you posted weren't anything I had seen.

It's right here, in the same message below:

> [tls @ 00000000004cc740] Creating security context failed (0x80090326) https://(link): Unknown error occurred

> `fmpeg.exe -i "%stream%"  -c copy -bsf:a aac_adtstoasc "output.mp4"`
> ...
> `yt-dlp .exe --downloader ffmpeg.exe https://(link) -o "output.mp4"`

Are `%stream%` and `https://(link)` a state secret? TLS has quite a number of configurable parameters (protocol version, cipher suite etc.) each of which can give a problem. Please provide an exact invocation with all URLs present.

**Comment by TehLandstander** [comment]
I don't know, does it?  I'm not clear on what information would be available from the link if I had to log into an account.

**Comment by nihil-admirari** [comment]
Can you please find a publicly available stream with which the issue still reproduces?

**Comment by TehLandstander** [comment]
Sorry, I've neen really busy, and I'll see what I can find.
The issue definitely seems to be multiWAN related. I dunno if that's an issue that anyone else cares if it's dealt with or not.
It's certainly not reproducible without a multiWAN setup.

**Comment by nihil-admirari** [comment]
I'll close the issue for now, since it appears to require a multiWAN to reproduce. Feel free to reopen if you manage to reproduce it without a multiWAN.

**Comment by badrelmers** [comment]
I get this error too with this build:  Creating security context failed (0x80090326)
it is because this ffmpeg was built with Windows SChannel/native TLS not openssl or gnutls
and windows 7 support only TLS 1.2 not 1.3, and not all 1.2 cipher suits, and today a lot of servers enable only few 1.2 ciphers like https://fastly.frontrowcdn.com , so they fail to work with this ffmpeg build, while they success with https://www.gyan.dev/ffmpeg/builds/ because it was built with gnutls because it does not use the old Windows SChannel/native TLS

to check which tls your ffmpeg was built with run:
ffmpeg -buildconf | findstr /i "openssl gnutls schannel"

**Comment by nihil-admirari** [comment]
Windows 7 is not supported anymore: https://github.com/yt-dlp/FFmpeg-Builds/issues/61/. Workflow's author is [against using non-system TLS on Windows](https://github.com/BtbN/FFmpeg-Builds/issues/373):
> Using an OS provided tls library which gets regular updates is largely preferable over a forever frozen in time version of openssl.
  
> ... it's not in any way or form an immature backend and supposed to work just fine.
  
> Also keep in mind that a statically linked openssl on Windows has no means to access any certificate store or anything, so I think will just blindly accept anything unless pointed at a cert store manually, which ffmpeg does not do.
(That's also an issue on Linux, but there sadly is no good alternative there)
  
> [talking about FFmpeg SChannel backend issues] Please actually report them: https://trac.ffmpeg.org/
You're not the first person mentioning issues with schannel, but nobody ever followed up with any way to reproduce them, let alone get them fixed.
And I myself never ran into any issues with it.
