### ISSUE TITLE
URLs are down

### ISSUE THREAD

**Issue by mshaevitch** [yt-dlp/FFmpeg-Builds#38]
The download links for the Linux and Windows builds are down (example: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz)

**Comment by vinismarques** [comment]
Realized just this when the Docker build failed.

**Comment by pukkandan** [comment]
Happened due to a workflow failure. Fixed now
