### ISSUE TITLE
[question] any patches/fixes that applied here and are not present in https://github.com/nanake/ffmpeg-tinderbox/

### ISSUE THREAD

**Issue by ghost** [yt-dlp/FFmpeg-Builds#39]
https://github.com/nanake/ffmpeg-tinderbox/ has a nightly builds from the ffmpeg repo,  
along with nonfree libraries like hevc, libfdk-aac and decklink, it seems faster too.  
anyone maintaining this repo can tell if there are additional fixed that were applied that are not part of the ffmpeg repo, so I'll suggest to add them to the other build?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/FFmpeg-Builds#patches-applied

**Comment by ghost** [comment]
[thank you](https://github.com/yt-dlp/FFmpeg-Builds/commit/b2480670accc05ceb0501ad220b386094e7d085b)  
that is helpful.
