### ISSUE TITLE
How to convert your doc/ffmpeg*.html to TROFF standard manpages ?

### ISSUE THREAD

**Issue by sebma** [yt-dlp/FFmpeg-Builds#41]
Hi, how can I convert your doc/ffmpeg*.html from your ffmpeg release to  Linux manpages ?

**Comment by nihil-admirari** [comment]
If I'm not mistaken, man pages are simply not packaged: https://github.com/yt-dlp/FFmpeg-Builds/blob/master/variants/default-install.sh#L11.

**Comment by nihil-admirari** [comment]
They're packaged now. Probably this feature better be merged upstream.

**Comment by sebma** [comment]
@nihil-admirari Thanks.
