### ISSUE TITLE
Question : BtbN/FFmpeg-Builds vs yt-dlp/FFmpeg-Builds

### ISSUE THREAD

**Issue by sebma** [yt-dlp/FFmpeg-Builds#43]
Hi, I have noticed your project is a fork of BtbN/FFmpeg-Builds. 

What is the differences between the two ?

In which case should I choose the first over the second ?

**Comment by pukkandan** [comment]
Read the readme

**Comment by sebma** [comment]
@pukkandan Oups 😄 
By the way, I can read  in your `README.md` : 

> This repository provides static Windows (x86 and x86_64) and Linux (x86_64, arm64) Builds of [FFmpeg master](https://github.com/FFmpeg/FFmpeg) and [latest release branch](https://github.com/FFmpeg/FFmpeg/tree/release/4.4) **_with some patches necessary for smooth integration with [yt-dlp](https://github.com/yt-dlp/yt-dlp)_**

What do you mean by **_with some patches necessary for smooth integration with [yt-dlp](https://github.com/yt-dlp/yt-dlp)_** ?

Can you tell me more about these necessary patches ?

**Comment by pukkandan** [comment]
Literally just keep reading!

![image](https://github.com/yt-dlp/FFmpeg-Builds/assets/6623388/df2bb2e8-b903-43b6-907f-7c2764de77ed)

**Comment by sebma** [comment]
@pukkandan My bad, I must really be tired :laughing: 

Sorry for the inconvenience.
