### ISSUE TITLE
Downloads Lead to 404

### ISSUE THREAD

**Issue by schubydoo** [yt-dlp/FFmpeg-Builds#45]
FYI these links:

![image](https://github.com/yt-dlp/FFmpeg-Builds/assets/12485317/89e376d2-4810-49bd-bc18-4cdc05b39e36)

Lead to 404 pages.

**Comment by ghost** [comment]
All of the `*-master-latest-*` artifacts are gone, even from old releases.

**Comment by ATypescriptEnjoyer** [comment]
Seems like this has now been fixed
