### ISSUE TITLE
Update builds and patches for FFmpeg 6.1

### ISSUE THREAD

**Issue by antermin** [yt-dlp/FFmpeg-Builds#49]
The latest stable release of FFmpeg is 6.1, and some distros (e.g. Arch, OpenMandriva Rolling) have already updated to FFmpeg 6.1.

Currently the repo has [patches for 6.0](https://github.com/yt-dlp/FFmpeg-Builds/tree/master/patches/ffmpeg/release/6.0) but not 6.1, and the [Latest Auto-Build (2023-11-21 14:09)](https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/latest) is 6.0.

**Comment by nihil-admirari** [comment]
Done.
