### ISSUE TITLE
[Feature Request] Alpine Linux build

### ISSUE THREAD

**Issue by jmbannon** [yt-dlp/FFmpeg-Builds#53]
As I understand, Alpine Linux links differently than typical Linux builds. I tried downloading and running the executable along with Alpine's `libc6-compat` package, and got many `symbol not found` errors.

Since this builds from source, I think a github workflow could be added to do the build within an alpine linux docker container.
This would be beneficial to many docker containers that use Alpine

**Comment by nihil-admirari** [comment]
Such requests should go upstream https://github.com/BtbN/FFmpeg-Builds, not here.

Actually, someone already requested such a feature: https://github.com/BtbN/FFmpeg-Builds/issues/105. Author's responses are as follows

https://github.com/BtbN/FFmpeg-Builds/issues/105#issuecomment-935953971
> But the by far biggest showstopper is that when not using the normal glibc dynamic linker, unsurprisingly dynamic linking stops working.
>
> FFmpeg dlopens a ton of its dependencies though. So using musl would come at the cost of no more CUDA, nvenc, nvdec, vaapi, Vulkan, avisynth, ladspa/lv2, and probably a bunch of other stuff I forgot about.
>
> So, musl is not really a realistic option.

https://github.com/BtbN/FFmpeg-Builds/issues/105#issuecomment-936068731:
> dlopen might work in a pure musl environment, given musl acts as dynamic loader there, and the libs it loads are also linked against musl.
>
> But almost nobody will be using a musl based system to run the binaries produced here, so that's not something to rely on. Also, doing that would make it impossible to run the binaries on glibc systems, which is even less of an option.
