### ISSUE TITLE
HEVC-over-FLV has two standards, but FFmpeg only implements one of them.

### ISSUE THREAD

**Issue by delhi2050** [yt-dlp/FFmpeg-Builds#56]
HEVC-over-FLV has two standards, but FFmpeg only implements one of them.

Standard 1: codecid=12 for HEVC
Standard 2: enhanced-rtmp

The patch that was removed in history only implemented Standard 1, but did not implement Standard 2. 
In FFmpeg 6.1, only Standard 2 is implemented and not Standard 1.

I have created a patch that supports both standards of HEVC-over-FLV and I hope it will be merged into the current project.

https://github.com/delhi2050/FFmpeg-Builds/blob/master/patches/ffmpeg/master/0002-Support-for-HEVC-over-FLV.patch

**Comment by pukkandan** [comment]
Is there a related yt-dlp issue?

**Comment by delhi2050** [comment]
> Is there a related yt-dlp issue?

No, given that the live streams on Chinese sites uses the first standard _codecid=12_, this may cause ffmpeg not function properly.

**Comment by nihil-admirari** [comment]
Your patch still uses

```diff
+        ret = 3;    // not 4, reading packet type will consume one byte
```

which seems no longer necessary in the light of https://github.com/FFmpeg/FFmpeg/commit/6dd5f9509334f53a4217540d430360d49578ecee. I've modified the patch, and now it's substantially simpler.

I don't have access to any non-standard HEVC-in-FLV videos. The issue will remain open until someone confirms that the patch actually works.

**Comment by delhi2050** [comment]
I have uploaded two videos encoded with both standards

https://github.com/delhi2050/flv-hevc-test-video

**Comment by nihil-admirari** [comment]
The latest `ffplay` plays both of these videos. Builds before the patch play only the standard enhanced-rtmp (codec ID 12 is non-standard and unofficial). Closing the issue.
