### ISSUE TITLE
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000265dad6e740] moov atom not found pipe:0: Invalid data found when processing input

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/FFmpeg-Builds#57]
youtube-dl -o - -f '140+134' https://www.youtube.com/watch?v=InweWI41HFE | ffmpeg -re -f mp4 -i pipe:0 -c:a copy -ac 1 -ar 44100 -b:a 128k -c:v libx264 -tune psnr -f flv -b:v 1.5M -maxrate 1.5M -bufsize 3M -g 60 -preset veryfast rtmps://live-api-s.facebook.com:443/rtmp/FB-429913729717319-0-AbyZanKVcZhh3jyH
[youtube] Extracting URL: https://www.youtube.com/watch?v=InweWI41HFE
[youtube] InweWI41HFE: Downloading webpage
[youtube] InweWI41HFE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] InweWI41HFE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] InweWI41HFE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] InweWI41HFE: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] InweWI41HFE: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = sPecqnfUe7cGTXB ; player = https://www.youtube.com/s/player/9383995e/player_ias.vflset/en_US/base.js
WARNING: [youtube] InweWI41HFE: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = TF3nm1b0D3Vd0N6 ; player = https://www.youtube.com/s/player/9383995e/player_ias.vflset/en_US/base.js
[info] InweWI41HFE: Downloading 1 format(s): 140+134
[download] Destination: -
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://rr1---sn-hx3voboxu-2oil.googlevideo.com/videoplayback?expire=1711615962&ei=edsEZsTbPIuU1d8P1fSU-AU&ip=202.57.209.213&id=o-AKis3gRMZpXOWifKER4agAP1ew8UEgM2ydUs-OmjXZ5P&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=8H&mm=31%2C29&mn=sn-hx3voboxu-2oil%2Csn-30a7rned&ms=au%2Crdu&mv=m&mvi=1&pl=26&initcwndbps=867500&spc=UWF9f3O5jRIQMNSfyTFfIReNtYVlC8_aWZaFxfuREm2GXSA&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=Lsx35970YgEvU1-SlLQSlI4Q&gir=yes&clen=11389011&dur=703.680&lmt=1711259128025150&mt=1711593894&fvip=2&keepalive=yes&fexp=51141542&c=WEB&sefc=1&txp=5532434&n=TF3nm1b0D3Vd0N6&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgRJGOxXFDq9YzVav0a45UXIvstElYcFDUcXIVvLmONmsCIAjeMNzkNGeefGRCPokxYIQ_DdhGwIoWTdFQME8x6Bv5&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRgIhANr5EfJrzV0k_ioi8NZ8f84nJqIqprdHeeqdsg9bOlLzAiEA0ur5qCGMpN1v4ZLAxwj-L15VJjOsPUe8Zaj5-dmv0LY%3D':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2024-03-24T05:44:44.000000Z
  Duration: 00:11:43.68, start: 0.000000, bitrate: 129 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 1 kb/s (default)
    Metadata:
      creation_time   : 2024-03-24T05:44:44.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'https://rr1---sn-hx3voboxu-2oil.googlevideo.com/videoplayback?expire=1711615962&ei=edsEZsTbPIuU1d8P1fSU-AU&ip=202.57.209.213&id=o-AKis3gRMZpXOWifKER4agAP1ew8UEgM2ydUs-OmjXZ5P&itag=134&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=8H&mm=31%2C29&mn=sn-hx3voboxu-2oil%2Csn-30a7rned&ms=au%2Crdu&mv=m&mvi=1&pl=26&initcwndbps=867500&spc=UWF9f3O5jRIQMNSfyTFfIReNtYVlC8_aWZaFxfuREm2GXSA&vprv=1&svpuc=1&mime=video%2Fmp4&ns=Lsx35970YgEvU1-SlLQSlI4Q&gir=yes&clen=27651575&dur=703.633&lmt=1711264865159725&mt=1711593894&fvip=2&keepalive=yes&fexp=51141542&c=WEB&sefc=1&txp=5535434&n=TF3nm1b0D3Vd0N6&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAOGBRK9zN3rJT1g_xgXhJZGvVWEpCOz9Qu4foQUbTUcGAiBvX6eLpG6DQcaudF4LNFWEh6Zs7yrrKsVmGALe6yudiA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRgIhANr5EfJrzV0k_ioi8NZ8f84nJqIqprdHeeqdsg9bOlLzAiEA0ur5qCGMpN1v4ZLAxwj-L15VJjOsPUe8Zaj5-dmv0LY%3D':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6avc1mp41
    creation_time   : 2024-03-24T07:00:10.000000Z
  Duration: 00:11:43.63, start: 0.000000, bitrate: 314 kb/s
    Stream #1:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 2 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2024-03-24T07:00:10.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Output #0, mpegts, to 'pipe:':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    encoder         : Lavf58.45.100
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 1 kb/s (default)
    Metadata:
      creation_time   : 2024-03-24T05:44:44.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 2 kb/s, 30 fps, 30 tbr, 90k tbn, 15360 tbc (default)
    Metadata:
      creation_time   : 2024-03-24T07:00:10.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=21109 fps= 45 q=-1.0 Lsize=   44546kB time=00:11:43.65 bitrate= 518.6kbits/s speed= 1.5x
video:26740kB audio:10995kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 18.047729%
[download] 100% in 00:07:52
ffmpeg version 4.3.2-2021-02-02-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000265dad6e740] moov atom not found
pipe:0: Invalid data found when processing input

**Comment by bashonly** [comment]
> ffmpeg version 4.3.2-2021-02-02-full_build-www.gyan.dev

you are not using a build from this repo
