### ISSUE TITLE
Stream mapping:   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264)) Cannot determine format of input stream 0:0 after EOF Error marking filters as finished Conversion failed!

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/FFmpeg-Builds#58]
youtube-dl -o - https://www.youtube.com/watch?v=q3LSVW99Drw | ffmpeg -re -f mp4 -i pipe:0 -c:a copy -ac 1 -ar 44100 -b:a 128k -c:v libx264 -tune psnr -f flv -b:v 1.5M -maxrate 1.5M -bufsize 3M -g 60 -preset veryfast rtmps://live-api-s.facebook.com:443/rtmp/FB-429913729717319-0-AbyZanKVcZhh3jyH
[youtube] Extracting URL: https://www.youtube.com/watch?v=q3LSVW99Drw
[youtube] q3LSVW99Drw: Downloading webpage
[youtube] q3LSVW99Drw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] q3LSVW99Drw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] q3LSVW99Drw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] q3LSVW99Drw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] q3LSVW99Drw: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = bZUIGRGQQ3YqkW9 ; player = https://www.youtube.com/s/player/9383995e/player_ias.vflset/en_US/base.js
WARNING: [youtube] q3LSVW99Drw: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = juGOVyB7rTRPGaA ; player = https://www.youtube.com/s/player/9383995e/player_ias.vflset/en_US/base.js
[info] q3LSVW99Drw: Downloading 1 format(s): 18
[download] Destination: -
[download] 100% of   27.83MiB in 00:08:18 at 57.20KiB/s
ffmpeg version 4.3.2-2021-02-02-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000026c9838e740] overread end of atom 'stsd' by 39 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000026c9838e740] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 575x360): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:0':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
  Duration: 00:07:08.83, bitrate: N/A
    Stream #0:0(ui): Video: h264 (avc1 / 0x31637661), none, 575x360, 12288 tbr, 12288 tbn, 24576 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Cannot determine format of input stream 0:0 after EOF
Error marking filters as finished
Conversion failed!

**Comment by bashonly** [comment]
> ffmpeg version 4.3.2-2021-02-02-full_build-www.gyan.dev

wrong repo, and extremely outdated version
