### ISSUE TITLE
[Question] What is this ID in the filename?

### ISSUE THREAD

**Issue by 54m4d** [yt-dlp/FFmpeg-Builds#59]
Hi!

I'm wondering if that alphanumeric string **`gd38bf5e08e`** in the file name is a commit ID?

E.g, in `ffmpeg-n7.0-7-gd38bf5e08e-win64-gpl-7.0.zip`, is `gd38bf5e08e` the commit ID? Also, how can I use this ID to check out the commit history in the original FFmpeg and check what's been changed?

Thanks!

**Comment by bashonly** [comment]
remove the `g` prefix and it is a commit hash, yeah

you can then append it to `https://github.com/ffmpeg/ffmpeg/commit/` e.g. https://github.com/ffmpeg/ffmpeg/commit/d38bf5e08e


or to see the history up until that commit you can then append it to `https://github.com/ffmpeg/ffmpeg/commits/` e.g. https://github.com/ffmpeg/ffmpeg/commits/d38bf5e08e

or if you have ~500MB to spare on your disk you can clone the repo and use `git log`

**Comment by 54m4d** [comment]
This answers my question. Thank you!
