### ISSUE TITLE
Build for ARMv8 Architecture?

### ISSUE THREAD

**Issue by threehappypenguins** [yt-dlp/FFmpeg-Builds#60]
I was hoping to build for my armv8 system so I could use it on there since I am having trouble with yt-dlp downloading and merging together video and audio files. I cannot figure out how I'm supposed to build it. Can I get some help?

**Comment by nihil-admirari** [comment]
There are some builds for Linux and Windows on ARM, you can find them in the [releases](https://github.com/yt-dlp/FFmpeg-Builds/releases): [ffmpeg-master-latest-linuxarm64-gpl.tar.xz](https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linuxarm64-gpl.tar.xz) and [ffmpeg-master-latest-winarm64-gpl-shared.zip](https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-winarm64-gpl-shared.zip).

If these builds do not work on your particular ARM system, please file an issue upstream: https://github.com/BtbN/FFmpeg-Builds.
