### ISSUE TITLE
win64 builds broken on Windows 7 as of Auto-Build 2024-05-11

### ISSUE THREAD

**Issue by EatDesk** [yt-dlp/FFmpeg-Builds#61]
Hello,

I typically update ffmpeg from this repository when a yt-dlp update is released and I have just found that ffmpeg is broken on Windows 7 x64 with the following message shown when attempting to run it:

![err](https://github.com/yt-dlp/FFmpeg-Builds/assets/50457062/8dd9cdc5-feb6-4bfb-83a8-069a09b7b12f)

Going back through the builds I found the last working auto build to be: https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/autobuild-2024-04-30-14-09

Which points to one of the following being the breaking commit https://github.com/yt-dlp/FFmpeg-Builds/compare/autobuild-2024-04-30-14-09...master

Upstream ffmpeg still works on Windows 7 as of `Latest Auto-Build (2024-05-26 12:46)` so this issue is specific to this fork.

If it's possible to still support legacy windows in the current yt-dlp ffmpeg builds that would be appreciated. Thank you.

edit: this issue only affects win64 builds, win32 builds are unaffected

**Comment by nihil-admirari** [comment]
> Upstream ffmpeg still works on Windows 7

There are no changes here that use WinAPI directly, so there shouldn't be an incompatibility that is not already present upstream.

However, upstream currently publishes master, 5.1, 6.1, and 7.0 versions of FFmpeg. This repository—only master and 7.0. So the question is: which upstream version you've been able to successfully run on Windows 7? Are upstream master and 7.0 still compatible with Windows 7?

**Comment by EatDesk** [comment]
Hi @nihil-admirari 

To confirm the following upstream builds from today don't exhibit the behaviour and work fine on Windows 7:

`Latest Auto-Build (2024-05-27 12:46)`
https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.0-latest-win64-gpl-7.0.zip

The equivalent yt-dlp ffmpeg fork builds from `Latest Auto-Build (2024-05-27 14:08)` do exhibit the behaviour.

**Comment by DOSforever** [comment]
Yes, I'm also using Windows 7 x64, yt-dlp ffmpeg fork builds from `Auto-Build 2024-05-28 14:17` also having the same issue. 
So which version is the latest for Windows 7?

**Comment by nihil-admirari** [comment]
Are you using shared or static builds (question applies to both this repository and upstream)?

**Comment by EatDesk** [comment]
I tested both and it's the same result: upstream builds all work but the ones in this repository all give the error.

**Comment by nihil-admirari** [comment]
Ok, I've looked at the changes more carefully and found that normal builds were using quickbuild, which mustn't have been there but apparently crept up during one of the rebases. When https://github.com/yt-dlp/FFmpeg-Builds/actions/runs/9292626352 finishes, please test.

However, if it doesn't solve the problem then I'm out of any ideas.

**Comment by EatDesk** [comment]
Thanks for looking into it, I've just checked and unfortunately the now published `Latest Auto-Build (2024-05-29 21:56)` release presents the same issue.

**Comment by nihil-admirari** [comment]
Have you tried 32-bit builds?

**Comment by EatDesk** [comment]
> Have you tried 32-bit builds?

For some reason I actually had not! The win32 builds appear to be unaffected and are working fine.

**Comment by nihil-admirari** [comment]
This issue was mentioned in https://github.com/vxiiduu/VxKex/issues/259, which leads to https://github.com/GyanD/codexffmpeg/issues/136. From that issue:

https://github.com/GyanD/codexffmpeg/issues/136#issuecomment-2137241009:

> So some external dependency exclusive to the full build has started to call functions from the missing DLL. There are dozens of ext deps. so this could be hard to pinpoint.

https://github.com/GyanD/codexffmpeg/issues/136#issuecomment-2144538336
> … SDL. It is set to [dynamically load](https://github.com/libsdl-org/SDL/blob/main/src/thread/windows/SDL_syssem.c#L338) this DLL to access two functions only available on Windows 8 or later.

https://github.com/GyanD/codexffmpeg/issues/136#issuecomment-2147215357
> … libjxl. They started using C++ standard lib for [memory management](https://github.com/libjxl/libjxl/commit/8835f5dfc4857f46277f6c703e47ac7817bd7aed) recently. However, the .pc file wasn't changed to statically link the standard lib as noted https://github.com/libjxl/libjxl/issues/3627.

https://github.com/GyanD/codexffmpeg/issues/136#issuecomment-2160417697:
> there's another lib rav1e that also started linking to host libs

https://github.com/GyanD/codexffmpeg/issues/136#issuecomment-2171828878
> So, rust, the compiler for rav1e, [no longer supports](https://blog.rust-lang.org/2023/08/24/Rust-1.72.0.html#future-windows-compatibility) Windows 7. Which means the full build can't work on Windows 7 (without dropping rav1e). **I'm afraid that's the end of the road.**

Looks like it is not fixable. For some people, upstream of this repository [also stopped working](https://github.com/GyanD/codexffmpeg/issues/136#issuecomment-2171752053)
> BtbN ffmpeg-master-latest-win64-gpl build fails with the same error message. "This application was unable to start correctly (0xc0000005)."

If you really need Windows 7 support, try https://github.com/vxiiduu/VxKex/. https://github.com/vxiiduu/VxKex/issues/259
> Current Windows binaries claim to be compatible with "Windows 7 and above" but just throw an error **without VxKex**

can be read as implying that with VxKex FFmpeg doesn't throw.
