### ISSUE TITLE
Rookie Question: What is the fundamental built for a MacOs space?

### ISSUE THREAD

**Issue by VisualNodeLLC** [yt-dlp/FFmpeg-Builds#62]
Hello, 
I'm a student. Is there a basic guide about how to do the buildup of FFmpeg on MacOs using Terminal? 
Thanks for the help

**Comment by bashonly** [comment]
This question is out-of-scope. This repo can't produce macOS builds so this isn't the place to ask. See https://github.com/yt-dlp/FFmpeg-Builds/issues/51

If you just need to know how to install an up-to-date version of ffmpeg on macOS, use [homebrew](https://brew.sh)

**Comment by nihil-admirari** [comment]
If you want a patched version on macOS you can try the following.

1. Pick https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/blob/master/Formula/ffmpeg.rb or https://github.com/Homebrew/homebrew-core/blob/master/Formula/f/ffmpeg.rb as the base.
2. These files already have
    ```rb
      patch do
        url "https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/raw/5670ccd86d3b816f49ebc18cab878125eca2f81f/add-av_stream_get_first_dts-for-chromium.patch"
        sha256 "57e26caced5a1382cb639235f9555fc50e45e7bf8333f7c9ae3d49b3241d3f77"
      end
    ```
    You'd need to add a similar block that points to https://github.com/yt-dlp/FFmpeg-Builds/tree/master/patches/ffmpeg.
3. Make homebrew install FFmpeg from a patched formula.
