### ISSUE TITLE
FFmpeg illegal instruction

### ISSUE THREAD

**Issue by chaos7x** [yt-dlp/FFmpeg-Builds#66]
All builds after autobuild-2024-07-30-14-10 cause an "illegal instruction" error.

**Comment by nihil-admirari** [comment]
OS, processor? Is reproducible upstream?

**Comment by chaos7x** [comment]
AMD Turion(tm) II Neo N54L Dual-Core Processor
OS: Debian Bookworm.

**Comment by nihil-admirari** [comment]
From https://www.x86-guide.net/en/cpu/AMD-Turion-II-Neo-N54L-cpu-no8026.html

> Release date	April 26th 2010

Apparently it simply doesn't support any instruction sets introduced after 2010. Let's check with the author: https://github.com/BtbN/FFmpeg-Builds/issues/411.

**Comment by chaos7x** [comment]
That's not good.
I only need ffmpeg to download and mux the files from YouTube. :-(

**Comment by nihil-admirari** [comment]
The workflow author [needs the details](https://github.com/BtbN/FFmpeg-Builds/issues/411#issuecomment-2461032987) about the specific instructions causing the issue. Can you please run `ffmpeg` under `gdb` as outlined in https://stackoverflow.com/a/40223712/19055149 and provide the output?

**Comment by nihil-admirari** [comment]
Another person provided the relevant information upstream. Closing this one.
