### ISSUE TITLE
[Question] Why not use ffmpeg version 7+?

### ISSUE THREAD

**Issue by agreedSkiing** [yt-dlp/FFmpeg-Builds#68]
Just looked at the documentation and it points me to the ffmpeg release 6.1 and not really the latest version which is as of writing this 7.1.

Is that on purpose that this build isn't using a newer version of ffmpeg that has a fix for the `STYLE` and other blocks (https://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavformat/webvttdec.c;h=6e60348764fd3350cc4f0645ec97ae9c27e9bb66;hb=refs/heads/release/7.1#l95 or from the linked github https://github.com/FFmpeg/FFmpeg/blob/release/7.1/libavformat/webvttdec.c#L95)?

**Comment by bashonly** [comment]
What documentation are you referring to?

**Comment by agreedSkiing** [comment]
The readme.md https://github.com/yt-dlp/FFmpeg-Builds/blob/master/README.md, where second link (https://github.com/yt-dlp/FFmpeg-Builds/blob/master/README.md?plain=1#L4) after the heading points to release 6.1

**Comment by nihil-admirari** [comment]
The links simply wasn't updated in time. Actual releases use 7.1.
